### ISSUE TITLE
Throwing error on popup.js file - Requires fix

### ISSUE THREAD

**Issue by Gupta-Suruchi** [Jaishreebala/Invert.io#2]
popup.js:19 Uncaught TypeError: Cannot read properties of undefined (reading 'executeScript')
    at HTMLDivElement.<anonymous> (popup.js:19:25)
popup.js:27 Uncaught TypeError: Cannot read properties of undefined (reading 'executeScript')
    at HTMLDivElement.<anonymous> (popup.js:27:25)
popup.js:19 Uncaught TypeError: Cannot read properties of undefined (reading 'executeScript')
    at HTMLDivElement.<anonymous> (popup.js:19:25)
<img width="1673" alt="Screenshot 2024-02-17 at 6 25 19 PM" src="https://github.com/Jaishreebala/Invert.io/assets/149289690/b48302fa-ddce-4846-950f-532fbb9e7915">

**Comment by Gupta-Suruchi** [comment]
Hi @Jaishreebala, can you please look into it. I would like to fix this issue if you allow me to :)
